# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-28 09:55
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(choices=[('http', 'HTTP Process')], default='http', max_length=32)),
                ('schema', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='schema')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_process_process', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Processes',
            },
        ),
        migrations.CreateModel(
            name='ProcessLocker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('rules', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Rules config, tells us which process will be called based on what rules.', null=True, verbose_name='Process rules')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_process_processlocker', to=settings.AUTH_USER_MODEL)),
                ('processes', models.ManyToManyField(to='process.Process')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
