# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 07:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required. 30 characters or fewer.', max_length=30, verbose_name='Process Name')),
                ('code', models.CharField(help_text='Required & Unique. 30 characters or fewer.', max_length=30, unique=True, verbose_name='Process code')),
                ('resource_token', models.CharField(blank=True, help_text='Toke of Resource to which this Process belongs too.', max_length=30, null=True, verbose_name='Resource Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Non-editable, to be generated by system itself.', verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Process',
                'ordering': ['-created_at'],
                'verbose_name_plural': 'Processes',
            },
        ),
        migrations.CreateModel(
            name='ProcessLocker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required. 30 characters or fewer.', max_length=30, verbose_name='Process Locker Name')),
                ('rules', django.contrib.postgres.fields.jsonb.JSONField(help_text='Rules config, tells us which process will be called based on what rules.', verbose_name='Process rules')),
                ('token', models.UUIDField(blank=True, editable=False, help_text='Non-editable, to be generated by system itself and only when is_publish=True ,                    means when Process Locker is Published.', null=True, unique=True, verbose_name='Resource token')),
                ('is_publish', models.BooleanField(default=False, help_text='Only Publish When you are sure. Once published Lolcker cannot be updated.', verbose_name='Publish Locker')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Non-editable, to be generated by system itself.', verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Process`s Locker',
                'ordering': ['-created_at'],
                'verbose_name_plural': 'Process`s Locker',
            },
        ),
    ]
