# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_auto_20170117_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='operation',
            field=models.CharField(default=1, help_text='Operation of Resource to which this Process will call', max_length=255, verbose_name='Resource operation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='process',
            name='resource_token',
            field=models.CharField(default=1, help_text='Token of Resource to which this Process belongs too.', max_length=30, verbose_name='Resource Token'),
            preserve_default=False,
        ),
    ]
