# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_auto_20170117_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='resource_token',
            field=models.UUIDField(help_text='Token of Resource to which this Process belongs too.', verbose_name='Resource Token'),
        ),
        migrations.AlterField(
            model_name='processlocker',
            name='name',
            field=models.CharField(help_text='Required. 30 characters or fewer.', max_length=30, verbose_name='Locker Name'),
        ),
        migrations.AlterField(
            model_name='processlocker',
            name='token',
            field=models.UUIDField(blank=True, editable=False, help_text='Non-editable, to be generated by system itself and only when is_publish=True ,                    means when Process Locker is Published.', null=True, unique=True, verbose_name='Locker token'),
        ),
    ]
