# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-06 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_auto_20170602_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='is_system',
        ),
    ]
