# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_auto_20170117_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processlogs',
            name='process',
        ),
        migrations.DeleteModel(
            name='ProcessLogs',
        ),
    ]
