# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_auto_20170118_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processlocker',
            name='is_publish',
            field=models.BooleanField(default=False, help_text='Only Publish When you are sure. Once published Locker cannot be updated.', verbose_name='Publish Locker'),
        ),
    ]
