# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0006_auto_20170119_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='code',
        ),
        migrations.AddField(
            model_name='process',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, help_text='Process token, process is accessed via this token.', verbose_name='Process token'),
        ),
    ]
