# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-25 06:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0007_auto_20170120_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='endpoint_schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, help_text='A part of Schema from the Swagger Client from the resource server', verbose_name='schema'),
            preserve_default=False,
        ),
    ]
