# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-30 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0008_process_endpoint_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='processlocker',
            name='processes',
            field=models.ManyToManyField(to='process.Process'),
        ),
    ]
