# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 10:54
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0010_auto_20170222_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processlocker',
            name='rules',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Rules config, tells us which process will be called based on what rules.', null=True, verbose_name='Process rules'),
        ),
    ]
