# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 10:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('process', '0011_auto_20170228_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='processlocker',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author_process_processlocker', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
