# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-09 07:25
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('process', '0012_processlocker_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'verbose_name_plural': 'Processes'},
        ),
        migrations.RemoveField(
            model_name='process',
            name='endpoint_schema',
        ),
        migrations.RemoveField(
            model_name='process',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='process',
            name='resource_token',
        ),
        migrations.RenameField(
            model_name='process',
            old_name='token',
            new_name='uuid'
        ),
        migrations.AddField(
            model_name='process',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author_process_process', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='process',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='process',
            name='schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='schema'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process',
            name='type',
            field=models.CharField(choices=[('http', 'HTTP Process')], default='http', max_length=32),
        ),
        migrations.AlterField(
            model_name='process',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
