# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-09 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0013_auto_20170309_0725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processlocker',
            options={},
        ),
        migrations.RemoveField(
            model_name='processlocker',
            name='is_publish',
        ),
        migrations.RemoveField(
            model_name='processlocker',
            name='name',
        ),
        migrations.RenameField(
            model_name='processlocker',
            old_name='token',
            new_name='uuid'
        ),
        migrations.AddField(
            model_name='processlocker',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='processlocker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
