# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-09 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0014_auto_20170309_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processlocker',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
