# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 06:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vrt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runtimelocker',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='runtimelocker',
            old_name='updated_at',
            new_name='modified_on',
        ),
        migrations.RemoveField(
            model_name='runtime',
            name='user',
        ),
        migrations.AddField(
            model_name='runtime',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author_vrt_runtime', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runtime',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runtime',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='runtimelocker',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author_vrt_runtimelocker', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
