# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 06:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vrt', '0002_auto_20170118_0628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runtime',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='runtime',
            old_name='modified_on',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='runtimelocker',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='runtimelocker',
            old_name='modified_on',
            new_name='modified_at',
        ),
    ]
