# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vrt', '0003_auto_20170118_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtime',
            name='widget_locker_uuid',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
