# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 07:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vrt', '0004_runtime_widget_locker_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for each Session along with Runtime. Non-editable, to be generated by system itself.')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('runtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vrt.Runtime')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together=set([('uuid', 'runtime')]),
        ),
    ]
