# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-20 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vrt', '0005_auto_20170127_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtime',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='runtime',
            name='name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runtime',
            name='widget_locker_token',
            field=models.CharField(default='', help_text='Token of Widget Locker to which will be loaded when a runtime is called.', max_length=512, verbose_name='Widget Locker Token'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='runtime',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
