# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-21 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vrt', '0007_session_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtime',
            name='workflow_uuid',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
