import uuid

from django.conf import settings
from django.contrib import admin
from django.db import models
from django.utils.translation import ugettext_lazy as _

User = getattr(settings, 'AUTH_USER_MODEL', 'auth.User')


class Runtime(models.Model):
    # the user who created the runtime
    # just for audit purpose
    user = models.ForeignKey(User)

    uuid = models.UUIDField(
        default=uuid.uuid4,
        unique=True,
        editable=False,
        help_text=_('A unique identifier for each Runtime. '
                    'Non-editable, to be generated by system itself.'),
    )

    def __str__(self):
        return '{0}'.format(self.uuid)


@admin.register(Runtime)
class RuntimeAdmin(admin.ModelAdmin):
    raw_id_fields = ['user']
