# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 10:11
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(choices=[('none', 'None'), ('vrt', 'Veris RunTime'), ('widget', 'Widget'), ('process', 'Process'), ('resource', 'Resource')], default='none', help_text='Logs belongs to which actor', max_length=10, verbose_name='Log belongs to')),
                ('actorId', models.UUIDField(help_text='Actor id , so that we can identify an actor.', verbose_name='actor id')),
                ('session', models.UUIDField(help_text='Log session', verbose_name='Log Session id')),
                ('handshakeId', models.UUIDField(blank=True, help_text='Id of actor/service to whom execution is handover by any current service.', null=True, verbose_name='Handshake id')),
                ('dataIn', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Request payload, includes query_params, data etc.', null=True, verbose_name='Request payload')),
                ('dataOut', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Response that is returned via service.', null=True, verbose_name='Request response')),
                ('status', models.CharField(choices=[('init', 'Initialize'), ('in-progress', 'In Progress'), ('wait', 'Waiting'), ('fwd', 'Forward To'), ('succeeded', 'Completed'), ('failed', 'Failed')], default='init', help_text='Resource Request state at any given time.', max_length=20, verbose_name='current state of any request')),
                ('started_at', models.DateTimeField(db_index=True, help_text='When service initiated its task.', verbose_name='Service execution start time.')),
                ('ended_at', models.DateTimeField(db_index=True, help_text='When service completed its task.', verbose_name='Service execution end time.')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': 'Service Logs',
                'verbose_name_plural': 'Service Logs',
                'get_latest_by': 'id',
            },
        ),
    ]
