# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicelogs',
            name='actorId',
        ),
        migrations.AddField(
            model_name='servicelogs',
            name='actor_token',
            field=models.UUIDField(default=uuid.uuid4, help_text='Actor token , so that we can identify an actor.', verbose_name='Actor Token'),
            preserve_default=False,
        ),
    ]
