# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20170118_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelogs',
            name='ended_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When service completed its task.', null=True, verbose_name='Service execution end time.'),
        ),
    ]
