# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_auto_20170118_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicelogs',
            old_name='status',
            new_name='state',
        ),
        migrations.AddField(
            model_name='servicelogs',
            name='status_code',
            field=models.PositiveIntegerField(blank=True, help_text='Request status code sent in Response', null=True, verbose_name='Status code'),
        ),
    ]
