# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_auto_20170118_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicelogs',
            name='handshakeId',
        ),
        migrations.AddField(
            model_name='servicelogs',
            name='handshake_token',
            field=models.UUIDField(blank=True, help_text='Token of actor/service to whom execution is handover by any current service.', null=True, verbose_name='Handshake Token'),
        ),
    ]
