# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_auto_20170118_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelogs',
            name='handshake_status',
            field=models.BooleanField(default=False, help_text='Status of Handshake to whom execution is handover by any current service.', verbose_name='Handshake Status'),
        ),
    ]
