# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_servicelogs_handshake_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelogs',
            name='state',
            field=models.CharField(choices=[('init', 'Initialize'), ('in-progress', 'In Progress'), ('wait', 'Waiting'), ('handshake', 'Handshake'), ('handshake-succeed', 'Handshake Succeed'), ('handshake-failed', 'Handshake Failed'), ('succeeded', 'Completed'), ('failed', 'Failed')], default='init', help_text='Resource Request state at any given time.', max_length=20, verbose_name='current state of any request'),
        ),
    ]
