# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_auto_20170118_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelogs',
            name='actor_token',
            field=models.UUIDField(blank=True, help_text='Actor token , so that we can identify an actor.', null=True, verbose_name='Actor Token'),
        ),
        migrations.AlterField(
            model_name='servicelogs',
            name='state',
            field=models.CharField(choices=[('init', 'Initialize'), ('in-progress', 'In Progress'), ('wait', 'Waiting'), ('handshake_initialize', 'Handshake Initiated'), ('handshake-succeed', 'Handshake Succeed'), ('handshake-failed', 'Handshake Failed'), ('succeeded', 'Completed'), ('failed', 'Failed')], default='init', help_text='Resource Request state at any given time.', max_length=20, verbose_name='current state of any request'),
        ),
    ]
