# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WidgetConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32)),
                ('type', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='WidgetContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('is_required', models.BooleanField(default=True)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminals.Screen')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminals.Widget')),
            ],
        ),
        migrations.AddField(
            model_name='widget',
            name='config',
            field=models.ManyToManyField(to='terminals.WidgetConfiguration'),
        ),
        migrations.AddField(
            model_name='screen',
            name='widgets',
            field=models.ManyToManyField(related_name='widget_containers', through='terminals.WidgetContainer', to='terminals.Widget'),
        ),
    ]
