# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='config',
        ),
        migrations.AddField(
            model_name='widget',
            name='config',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='terminals.WidgetConfiguration'),
            preserve_default=False,
        ),
    ]
