# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0002_auto_20161129_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetcontainer',
            name='config',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='config',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='WidgetConfiguration',
        ),
    ]
