# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0004_auto_20161202_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=64)),
                ('terminal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='terminals.Terminal')),
            ],
        ),
    ]
