# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0006_event_webhook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screen',
            name='widgets',
        ),
        migrations.AlterField(
            model_name='widgetcontainer',
            name='widget',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='Widget',
        ),
    ]
