# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0007_auto_20161213_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='widgets',
            field=models.ManyToManyField(related_name='widget_containers', to='terminals.WidgetContainer'),
        ),
    ]
