# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-28 09:55
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Runtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('widget_locker_uuid', models.CharField(max_length=64)),
                ('widget_locker_token', models.CharField(help_text='Token of Widget Locker to which will be loaded when a runtime is called.', max_length=512, verbose_name='Widget Locker Token')),
                ('workflow_uuid', models.CharField(blank=True, max_length=512, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_runtime_runtime', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RuntimeLocker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Non-editable, to be generated by system itself.')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_runtime_runtimelocker', to=settings.AUTH_USER_MODEL)),
                ('runtimes', models.ManyToManyField(to='runtime.Runtime')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for each Session along with Runtime. Non-editable, to be generated by system itself.')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_runtime_session', to=settings.AUTH_USER_MODEL)),
                ('runtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runtime.Runtime')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together=set([('uuid', 'runtime')]),
        ),
    ]
