# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-29 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runtime', '0003_runtime_workflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runtime',
            name='workflow',
        ),
        migrations.RemoveField(
            model_name='runtime',
            name='workflow_uuid',
        ),
    ]
