# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-31 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0005_auto_20170529_1009'),
        ('runtime', '0004_auto_20170529_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtime',
            name='widgets',
            field=models.ManyToManyField(related_name='widget_runtime_runtime', to='widget.Widget', blank=True),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='widget_locker_token',
            field=models.CharField(blank=True, help_text='Token of Widget Locker to which will be loaded when a runtime is called.', max_length=512, null=True, verbose_name='Widget Locker Token'),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='widget_locker_uuid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
