# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 05:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runtime', '0007_session_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runtimelocker',
            name='author',
        ),
        migrations.RemoveField(
            model_name='runtimelocker',
            name='runtimes',
        ),
        migrations.DeleteModel(
            name='RuntimeLocker',
        ),
    ]
