# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 07:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('runtime', '0009_feedback'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together=set([('author', 'app')]),
        ),
    ]
