# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-25 12:14
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0003_auto_20170119_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Rules config, tells us which widget will be called based on what rules.', null=True, verbose_name='Widget Schema'),
        ),
    ]
