# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-30 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0004_auto_20170125_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetlocker',
            name='widgets',
            field=models.ManyToManyField(to='widgets.Widget'),
        ),
    ]
