# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 05:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0005_widgetlocker_widgets'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='template',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Widget Template, the list of components with their layout & styles', null=True, verbose_name='Widget Template'),
        ),
    ]
