# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-20 09:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('widgets', '0009_auto_20170301_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='widget',
            old_name='schema',
            new_name='processes_json'
        ),
        migrations.RenameField(
            model_name='widget',
            old_name='token',
            new_name='uuid'
        ),
        migrations.AddField(
            model_name='widget',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='widget',
            name='process_locker_token',
            field=models.CharField(help_text='Token of Process Locker to which will be loaded when a Widget is called.',
                                   max_length=512, verbose_name='Process Locker Token'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='processes_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
