# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-20 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0010_auto_20170320_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='widget',
            old_name='process_locker_token',
            new_name='process_locker_uuid'
        ),
        migrations.AddField(
            model_name='widget',
            name='process_locker_token',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='widget',
            name='process_locker_token',
            field=models.CharField(help_text='Token of Process Locker to which will be loaded when a Widget is called.',
                                   max_length=512, verbose_name='Process Locker Token'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='process_locker_uuid',
            field=models.CharField(max_length=512),
        ),
    ]
