# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-20 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('widgets', '0011_widget_process_locker_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='widgetlocker',
            options={},
        ),
        migrations.RemoveField(
            model_name='widgetlocker',
            name='is_publish',
        ),
        migrations.RemoveField(
            model_name='widgetlocker',
            name='name',
        ),
        migrations.RenameField(
            model_name='widgetlocker',
            old_name='token',
            new_name='uuid'
        ),
        migrations.AlterField(
            model_name='widgetlocker',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
