# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-20 11:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0012_auto_20170320_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='rules',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Widget Rules'),
        ),
        migrations.AddField(
            model_name='widget',
            name='workflow_uuid',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
