# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-18 11:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0002_widget_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='workflow',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
