# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-26 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0003_widget_workflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='processes_json',
        ),
    ]
