# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-29 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0004_remove_widget_processes_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='workflow',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='workflow_uuid',
        ),
    ]
