# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-31 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_auto_20170515_1242'),
        ('widget', '0005_auto_20170529_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='processes',
            field=models.ManyToManyField(related_name='widget_widget_widget', to='process.Process', blank=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='process_locker_token',
            field=models.CharField(blank=True, help_text='Token of Process Locker to which will be loaded when a Widget is called.', max_length=512, null=True, verbose_name='Process Locker Token'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='process_locker_uuid',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
