# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-02 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0006_auto_20170531_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
