# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-19 09:51
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


def process__to__process_configs(apps, schema_editor):
    Widget = apps.get_model('widget', 'Widget')
    Config = apps.get_model('widget', 'Config')
    for widget in Widget.objects.all():
        widget.config_set.add(
            *list(Config.objects.create(**{
                'author': widget.author,
                'process': process,
                'widget': widget,
                'config': (widget.data or {}).get(process.uuid, {})
            }) for process in widget.processes.all())
        )


def process_configs__to__process(apps, schema_editor):
    Widget = apps.get_model('widget', 'Widget')
    for widget in Widget.objects.all():
        widget.processes.add(
            *[config.process for config in widget.process_configs.all()]
        )


class Migration(migrations.Migration):
    dependencies = [
        ('process', '0006_auto_20170707_0828'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('widget', '0010_auto_20170707_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('config', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('transform', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('author',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_widget_config',
                                   to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Process')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='widget',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widget.Widget'),
        ),
        migrations.RunPython(process__to__process_configs, migrations.RunPython.noop),
        migrations.AddField(
            model_name='widget',
            name='process_configs',
            field=models.ManyToManyField(blank=True, through='widget.Config', to='process.Process'),
        ),
        migrations.AlterUniqueTogether(
            name='config',
            unique_together=set([('widget', 'process')]),
        )
    ]
