# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-13 11:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required. 30 characters or fewer.', max_length=30, verbose_name='resource name')),
                ('upstream_url', models.URLField(help_text='Required. 200 characters or fewer.', verbose_name='upstream url of resource.')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Non-editable, to be generated by system itself.', unique=True, verbose_name='Resource token, to be bind with process, Process will access Resource with the help of this               token. Generated by default, non-editable by user.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Non-editable, to be generated by system itself.', verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Resource',
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'verbose_name_plural': 'Resources',
            },
        ),
        migrations.CreateModel(
            name='ResourceLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logId', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Non-editable, to be generated by system itself.', unique=True, verbose_name='Log unique id, to be returned in response, logs can be fetched using this                 imporatent in case do not want to share your primary key')),
                ('started_at', models.DateTimeField(db_index=True, help_text='When resource initiated its task.', verbose_name='Resource execution start time.')),
                ('ended_at', models.DateTimeField(db_index=True, help_text='When resource completed its task.', verbose_name='Resource execution end time.')),
                ('dataIn', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Resource request payload, includes query_params, data etc.', null=True, verbose_name='Resource Request payload')),
                ('dataOut', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Response that is rerturned via Resource.', null=True, verbose_name='Resource Request response')),
                ('status', models.CharField(choices=[('init', 'Initialize'), ('inprocess', 'In Process'), ('wait', 'Waiting'), ('succeeded', 'Completed'), ('failed', 'Failed')], default='init', help_text='Resource Request state at any given time.', max_length=20, verbose_name='current state of resource request')),
                ('resource', models.ForeignKey(help_text='Resource to which this log belongs too.', on_delete=django.db.models.deletion.CASCADE, related_name='resource_logs', to='store.Resource', verbose_name='resource')),
            ],
            options={
                'get_latest_by': 'id',
                'verbose_name': 'Resource Logs',
                'ordering': ['-id'],
                'verbose_name_plural': 'Resources Logs',
            },
        ),
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together=set([('name', 'upstream_url')]),
        ),
    ]
