# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 07:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20170116_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, help_text='Resource swagger client schema.', verbose_name='Resource schema'),
            preserve_default=False,
        ),
    ]
