# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_resource_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Non-editable, to be generated by system itself.This token to be bind with process             Process will access Resource with the help of this token', unique=True, verbose_name='Resource token'),
        ),
        migrations.AlterField(
            model_name='resourcelogs',
            name='logId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Non-editable, to be generated by system itself. To be returned in response, logs can be             fetched using this important in case do not want to share your primary key', unique=True, verbose_name='Log unique id'),
        ),
    ]
