# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20170116_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcelogs',
            name='resource',
        ),
        migrations.DeleteModel(
            name='ResourceLogs',
        ),
    ]
