#!/usr/bin/python
# -*- coding: utf-8 -*-

import uuid

from django.conf import settings
from django.contrib import admin
from django.db import models
from django.utils.translation import ugettext_lazy as _

from asap.core.models import Authorable, Timestampable

User = getattr(settings, 'AUTH_USER_MODEL', 'auth.User')


class Widget(Authorable, Timestampable, models.Model):
    uuid = models.UUIDField(
        default=uuid.uuid4,
        unique=True,
        editable=False,
        help_text=_('A unique identifier for each Widget. '
                    'Non-editable, to be generated by system itself.'),
    )

    def __str__(self):
        return '{0}'.format(self.uuid)


@admin.register(Widget)
class WidgetAdmin(admin.ModelAdmin):
    raw_id_fields = ['author']
