# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='site',
        ),
    ]
