# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_remove_organization_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='runtime_locker_uuid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
