# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 06:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_auto_20170117_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='modified_on',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='modified_on',
            new_name='modified_at',
        ),
    ]
