# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 13:27
from __future__ import unicode_literals

import asap.utils
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_auto_20170118_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=asap.utils.media_folder),
        ),
    ]
