# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-21 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='auth_token',
            new_name='service_client_id',
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set([('organization', 'name')]),
        ),
    ]
