# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('organizations', '0002_auto_20161130_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='site',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
            preserve_default=False,
        ),
    ]
